### ISSUE TITLE
Problem with Dataset Folder

### ISSUE THREAD

**Issue by katieluo88** [quan-dao/practical-collab-perception#2]
Hi,

I'm trying to reproduce the results, and noticed that the link to the data appears to be incorrect. The zip file for [v2.0.zip](https://drive.google.com/file/d/1S91tdkpgW1uKgrVAbZLlk8l0ATftICgM/view?usp=drive_link) appears to only contain files for "v1.0-mini". Can the updated data link be provided?

Thanks.

**Comment by quan-dao** [comment]
Hi,

I renamed the folder from v1.0-mini to v2.0-mini while keeping the file unchanged.
